//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclaimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reclaimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scenario&gt;
        ///  &lt;section name=&quot;mission&quot;&gt;
        ///    &lt;enum16 name=&quot;Map Type&quot; offset=&quot;0x0&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;Single Player&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Multiplayer&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Main Menu&quot; value=&quot;0x2&quot; /&gt;
        ///    &lt;/enum16&gt;
        ///    &lt;flags16 name=&quot;Flags&quot; offset=&quot;0x2&quot; visible=&quot;true&quot;&gt;
        ///      &lt;bit name=&quot;Bit 0&quot; index=&quot;0&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 1&quot; index=&quot;1&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 2&quot; index=&quot;2&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 3&quot; index=&quot;3&quot; /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3Scenario {
            get {
                return ResourceManager.GetString("Halo3Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;node header=&quot;Mission&quot; type=&quot;Mission&quot;&gt;
        ///  &lt;node header=&quot;Objects&quot;&gt;
        ///    &lt;node header=&quot;Devices&quot;&gt;
        ///      &lt;node header=&quot;Machines&quot; type=&quot;Machines&quot; /&gt;
        ///      &lt;node header=&quot;Controls&quot; type=&quot;Controls&quot; /&gt;
        ///      &lt;node header=&quot;Light fixtures&quot; type=&quot;LightFixtures&quot; /&gt;
        ///      &lt;node header=&quot;Device groups&quot; type=&quot;DeviceGroups&quot; /&gt;
        ///    &lt;/node&gt;
        ///    &lt;node header=&quot;Items&quot;&gt;
        ///      &lt;node header=&quot;Equipment&quot; type=&quot;Equipment&quot; /&gt;
        ///      &lt;node header=&quot;Weapons&quot; type=&quot;Weapons&quot; /&gt;
        ///    &lt;/node&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeHierarchy {
            get {
                return ResourceManager.GetString("NodeHierarchy", resourceCulture);
            }
        }
    }
}
