//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclaimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reclaimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;plugin game=&quot;Halo3&quot; baseSize=&quot;0x7B8&quot;&gt;
        ///  &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x6C&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x30&quot; elementSize=&quot;0x14&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x3C&quot; elementSize=&quot;0x2C&quot;&gt;
        ///    &lt;tagblock offset=&quot;0x8&quot; elementSize=&quot;0x4&quot;/&gt;
        ///    &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x54&quot;&gt;
        ///      &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///        &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///          &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0x4&quot;/&gt;
        ///        &lt;/tagblock&gt;
        ///      &lt;/tagblock&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3Metadata {
            get {
                return ResourceManager.GetString("Halo3Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;plugin game=&quot;ODST&quot; baseSize=&quot;0x834&quot;&gt;
        ///  &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x6C&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x4C&quot; elementSize=&quot;0x14&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x58&quot; elementSize=&quot;0x2C&quot;&gt;
        ///    &lt;tagblock offset=&quot;0x8&quot; elementSize=&quot;0x4&quot;/&gt;
        ///    &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x54&quot;&gt;
        ///      &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///        &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///          &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0x4&quot;/&gt;
        ///        &lt;/tagblock&gt;
        ///      &lt;/tagblock&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3ODSTMetadata {
            get {
                return ResourceManager.GetString("Halo3ODSTMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scenario&gt;
        ///  &lt;section name=&quot;mission&quot;&gt;
        ///    &lt;enum8 name=&quot;Map Type&quot; offset=&quot;0x0&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;Single Player&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Multiplayer&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Main Menu&quot; value=&quot;0x2&quot; /&gt;
        ///    &lt;/enum8&gt;
        ///    &lt;enum8 name=&quot;Map Sub Type&quot; offset=&quot;0x1&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;None&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Hub&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Level&quot; value=&quot;0x2&quot; /&gt;
        ///      &lt;option name=&quot;Scene&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3ODSTScenario {
            get {
                return ResourceManager.GetString("Halo3ODSTScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scenario&gt;
        ///  &lt;section name=&quot;mission&quot;&gt;
        ///    &lt;enum16 name=&quot;Map Type&quot; offset=&quot;0x0&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;Single Player&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Multiplayer&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Main Menu&quot; value=&quot;0x2&quot; /&gt;
        ///    &lt;/enum16&gt;
        ///    &lt;flags16 name=&quot;Flags&quot; offset=&quot;0x2&quot; visible=&quot;true&quot;&gt;
        ///      &lt;bit name=&quot;Bit 0&quot; index=&quot;0&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 1&quot; index=&quot;1&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 2&quot; index=&quot;2&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 3&quot; index=&quot;3&quot; /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Halo3Scenario {
            get {
                return ResourceManager.GetString("Halo3Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;plugin game=&quot;Reach&quot; baseSize=&quot;0x86C&quot;&gt;
        ///  &lt;tagblock offset=&quot;0x4C&quot; elementSize=&quot;0xAC&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x58&quot; elementSize=&quot;0x20&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x84&quot; elementSize=&quot;0x30&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x90&quot; elementSize=&quot;0x2C&quot;&gt;
        ///    &lt;tagblock offset=&quot;0x8&quot; elementSize=&quot;0x4&quot;/&gt;
        ///    &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x48&quot;&gt;
        ///      &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///        &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///          &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0x4&quot;/&gt;
        ///        &lt;/tagblock&gt;
        ///      &lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HaloReachMetadata {
            get {
                return ResourceManager.GetString("HaloReachMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scenario&gt;
        ///  &lt;section name=&quot;mission&quot;&gt;
        ///    &lt;enum16 name=&quot;Map Type&quot; offset=&quot;0x0&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;Single Player&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Multiplayer&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Main Menu&quot; value=&quot;0x2&quot; /&gt;
        ///    &lt;/enum16&gt;
        ///    &lt;flags16 name=&quot;Flags&quot; offset=&quot;0x2&quot; visible=&quot;true&quot;&gt;
        ///      &lt;bit name=&quot;Bit 0&quot; index=&quot;0&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 1&quot; index=&quot;1&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 2&quot; index=&quot;2&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 3&quot; index=&quot;3&quot; /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HaloReachScenario {
            get {
                return ResourceManager.GetString("HaloReachScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;plugin game=&quot;ODSTMCC&quot; baseSize=&quot;0x840&quot;&gt;
        ///  &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x6C&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x4C&quot; elementSize=&quot;0x14&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x58&quot; elementSize=&quot;0x2C&quot;&gt;
        ///    &lt;tagblock offset=&quot;0x8&quot; elementSize=&quot;0x4&quot;/&gt;
        ///    &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x54&quot;&gt;
        ///      &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///        &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///          &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0x4&quot;/&gt;
        ///        &lt;/tagblock&gt;
        ///      &lt;/tagbloc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHalo3ODSTMetadata {
            get {
                return ResourceManager.GetString("MccHalo3ODSTMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scenario&gt;
        ///  &lt;section name=&quot;mission&quot;&gt;
        ///    &lt;enum8 name=&quot;Map Type&quot; offset=&quot;0x0&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;Single Player&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Multiplayer&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Main Menu&quot; value=&quot;0x2&quot; /&gt;
        ///    &lt;/enum8&gt;
        ///    &lt;enum8 name=&quot;Map Sub Type&quot; offset=&quot;0x1&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;None&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Hub&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Level&quot; value=&quot;0x2&quot; /&gt;
        ///      &lt;option name=&quot;Scene&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHalo3ODSTScenario {
            get {
                return ResourceManager.GetString("MccHalo3ODSTScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;plugin game=&quot;ReachMCC&quot; baseSize=&quot;0x884&quot;&gt;
        ///  &lt;tagblock offset=&quot;0x4C&quot; elementSize=&quot;0xAC&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x58&quot; elementSize=&quot;0x20&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x84&quot; elementSize=&quot;0x30&quot;/&gt;
        ///  &lt;tagblock offset=&quot;0x90&quot; elementSize=&quot;0x2C&quot;&gt;
        ///    &lt;tagblock offset=&quot;0x8&quot; elementSize=&quot;0x4&quot;/&gt;
        ///    &lt;tagblock offset=&quot;0x14&quot; elementSize=&quot;0x48&quot;&gt;
        ///      &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///        &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0xC&quot;&gt;
        ///          &lt;tagblock offset=&quot;0x0&quot; elementSize=&quot;0x4&quot;/&gt;
        ///        &lt;/tagblock&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHaloReachMetadata {
            get {
                return ResourceManager.GetString("MccHaloReachMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scenario&gt;
        ///  &lt;section name=&quot;mission&quot;&gt;
        ///    &lt;enum16 name=&quot;Map Type&quot; offset=&quot;0x0&quot; visible=&quot;true&quot;&gt;
        ///      &lt;option name=&quot;Single Player&quot; value=&quot;0x0&quot; /&gt;
        ///      &lt;option name=&quot;Multiplayer&quot; value=&quot;0x1&quot; /&gt;
        ///      &lt;option name=&quot;Main Menu&quot; value=&quot;0x2&quot; /&gt;
        ///    &lt;/enum16&gt;
        ///    &lt;flags16 name=&quot;Flags&quot; offset=&quot;0x2&quot; visible=&quot;true&quot;&gt;
        ///      &lt;bit name=&quot;Bit 0&quot; index=&quot;0&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 1&quot; index=&quot;1&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 2&quot; index=&quot;2&quot; /&gt;
        ///      &lt;bit name=&quot;Bit 3&quot; index=&quot;3&quot; /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MccHaloReachScenario {
            get {
                return ResourceManager.GetString("MccHaloReachScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;node header=&quot;Mission&quot; type=&quot;Mission&quot;&gt;
        ///  &lt;node header=&quot;Objects&quot;&gt;
        ///    &lt;node header=&quot;Devices&quot;&gt;
        ///      &lt;node header=&quot;Machines&quot; type=&quot;Machines&quot; /&gt;
        ///      &lt;node header=&quot;Controls&quot; type=&quot;Controls&quot; /&gt;
        ///      &lt;node header=&quot;Light fixtures&quot; type=&quot;LightFixtures&quot; visible=&quot;False&quot; /&gt;
        ///      &lt;node header=&quot;Device groups&quot; type=&quot;DeviceGroups&quot; visible=&quot;False&quot; /&gt;
        ///    &lt;/node&gt;
        ///    &lt;node header=&quot;Items&quot;&gt;
        ///      &lt;node header=&quot;Equipment&quot; type=&quot;Equipment&quot; /&gt;
        ///      &lt;node header=&quot;Weapons&quot; ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeHierarchy {
            get {
                return ResourceManager.GetString("NodeHierarchy", resourceCulture);
            }
        }
    }
}
